export const TableColumns = [
  {
    name: 'doc_retorno',
    label: 'Doc Retorno',
    align: 'left',
    field: 'doc_retorno',
    sortable: true,
  },
  {
    name: 'tipo_documento',
    label: 'Tipo Documento',
    align: 'left',
    field: 'tipo_documento',
    sortable: true,
  },
  {
    name: 'tipo_servicio',
    label: 'Tipo Servicio',
    align: 'left',
    field: 'tipo_servicio',
    sortable: true,
  },
  {
    name: 'nombre_cliente',
    label: 'Nombre Cliente',
    align: 'left',
    field: 'nombre_cliente',
    sortable: true,
  },
  { name: 'referencia', label: 'Referencia', align: 'left', field: 'referencia' },
  { name: 'observaciones1', label: 'Observaciones 1', align: 'left', field: 'observaciones1' },
  {
    name: 'poblacion_consignatario',
    label: 'Población Consignatario',
    align: 'left',
    field: 'poblacion_consignatario',
  },
  {
    name: 'nombre_consignatario',
    label: 'Nombre Consignatario',
    align: 'left',
    field: 'nombre_consignatario',
  },
  {
    name: 'direccion_consignatario',
    label: 'Dirección Consignatario',
    align: 'left',
    field: 'direccion_consignatario',
  },
  {
    name: 'contacto_consignatario',
    label: 'Contacto Consignatario',
    align: 'left',
    field: 'contacto_consignatario',
  },
  {
    name: 'telefono_consignatario',
    label: 'Teléfono Consignatario',
    align: 'left',
    field: 'telefono_consignatario',
  },
  {
    name: 'nif_consignatario',
    label: 'NIF Consignatario',
    align: 'left',
    field: 'nif_consignatario',
  },
  { name: 'bultos', label: 'Bultos', align: 'left', field: 'bultos' },
  { name: 'kilos', label: 'Kilos', align: 'left', field: 'kilos' },
  { name: 'volumen', label: 'Volumen', align: 'left', field: 'volumen' },
  { name: 'valor_seguro', label: 'Valor Seguro', align: 'left', field: 'valor_seguro' },
] as const; // Use 'as const' to make it a readonly tuple
